import spec from "../../../sdk/openapi.json";

type OpenAPISchema = {
  type?: string;
  properties?: Record<string, OpenAPISchema>;
  required?: string[];
  allOf?: OpenAPISchema[];
  oneOf?: OpenAPISchema[];
  anyOf?: OpenAPISchema[];
  items?: OpenAPISchema;
  $ref?: string;
  enum?: any[];
  const?: any;
  format?: string;
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  nullable?: boolean;
  additionalProperties?: boolean | OpenAPISchema;
  example?: any;
  [key: string]: any;
};

type OpenAPIDocument = {
  components?: { schemas?: Record<string, OpenAPISchema> };
  paths?: Record<string, Record<string, any>>;
};

const formats: Record<string, string> = {
  email: "user@example.com",
  "date-time": new Date().toISOString(),
  uuid: "00000000-0000-0000-0000-000000000000",
  uri: "https://example.com",
};

/**
 * Validates API responses against the OpenAPI spec generated by the Hono app.
 * Single source of truth: `bun run gen:spec` writes `packages/sdk/openapi.json`.
 */
export class SchemaValidator {
  private static async getSpec(): Promise<OpenAPIDocument> {
    return spec as OpenAPIDocument;
  }

  private static findOpenAPIPath(spec: OpenAPIDocument, path: string): string | undefined {
    const paths = spec.paths;
    if (!paths) return undefined;

    const normalized = path.startsWith("/") ? path : `/${path}`;
    if (paths[normalized]) return normalized;

    const parts = normalized.split("/").filter(Boolean);
    for (const candidate of Object.keys(paths)) {
      const candidateParts = candidate.split("/").filter(Boolean);
      if (parts.length !== candidateParts.length) continue;
      const match = candidateParts.every(
        (seg, i) => (seg.startsWith("{") && seg.endsWith("}")) || seg === parts[i],
      );
      if (match) return candidate;
    }
    return undefined;
  }

  private static deref(ref: string, spec: OpenAPIDocument, seen: Set<string>): OpenAPISchema {
    if (seen.has(ref)) return { type: "object" };
    const schema = spec.components?.schemas?.[ref.split("/").pop()!];
    if (!schema) throw new Error(`Unresolved $ref: ${ref}`);
    return this.resolve(structuredClone(schema), spec, new Set(seen).add(ref));
  }

  private static resolve(
    schema: OpenAPISchema,
    spec: OpenAPIDocument,
    seen: Set<string> = new Set(),
  ): OpenAPISchema {
    if (!schema) return schema;
    if (schema.$ref) return this.deref(schema.$ref, spec, seen);

    const walk = (s: OpenAPISchema) => this.resolve(s, spec, seen);
    const out = { ...schema };
    if (out.properties)
      out.properties = Object.fromEntries(
        Object.entries(out.properties).map(([k, v]) => [k, walk(v)]),
      );
    if (out.items) out.items = walk(out.items);
    for (const key of ["allOf", "oneOf", "anyOf"] as const)
      if (out[key]) out[key] = out[key]!.map(walk);
    return out;
  }

  private static union(
    data: any,
    list: OpenAPISchema[],
    errors: string[],
    path: string,
    kind: string,
  ): boolean {
    const ok = list.some((s) => this.validate(data, s, [], path));
    if (!ok) errors.push(`${path}: matched none of ${kind}`);
    return ok;
  }

  private static object(data: any, schema: OpenAPISchema, errors: string[], path: string): boolean {
    if (typeof data !== "object" || data === null || Array.isArray(data)) {
      errors.push(`${path}: expected object, got ${typeof data}`);
      return false;
    }
    const missing = (schema.required ?? []).filter((key) => !(key in data));
    missing.forEach((key) => errors.push(`${path}: missing required property "${key}"`));
    const bad = Object.entries(schema.properties ?? {})
      .filter(([key]) => key in data)
      .filter(([key, sub]) => !this.validate(data[key], sub, errors, `${path}.${key}`));
    return missing.length === 0 && bad.length === 0;
  }

  private static array(data: any, schema: OpenAPISchema, errors: string[], path: string): boolean {
    if (!Array.isArray(data)) {
      errors.push(`${path}: expected array, got ${typeof data}`);
      return false;
    }
    const errs: string[] = [];
    if (schema.minItems != null && data.length < schema.minItems)
      errs.push(`${path}: array too short (${data.length} < ${schema.minItems})`);
    if (schema.maxItems != null && data.length > schema.maxItems)
      errs.push(`${path}: array too long (${data.length} > ${schema.maxItems})`);
    errors.push(...errs);
    const items = schema.items;
    const bad = items
      ? data.filter((v, i) => !this.validate(v, items, errors, `${path}[${i}]`))
      : [];
    return errs.length === 0 && bad.length === 0;
  }

  private static text(data: any, schema: OpenAPISchema, errors: string[], path: string): boolean {
    if (typeof data !== "string") {
      errors.push(`${path}: expected string, got ${typeof data}`);
      return false;
    }
    if (schema.pattern && !new RegExp(schema.pattern).test(data)) {
      errors.push(`${path}: string does not match pattern ${schema.pattern}`);
      return false;
    }
    if (schema.minLength != null && data.length < schema.minLength) {
      errors.push(`${path}: string too short`);
      return false;
    }
    if (schema.maxLength != null && data.length > schema.maxLength) {
      errors.push(`${path}: string too long`);
      return false;
    }
    return true;
  }

  private static number(data: any, schema: OpenAPISchema, errors: string[], path: string): boolean {
    const type = schema.type ?? "number";
    if (typeof data !== "number") {
      errors.push(`${path}: expected ${type}, got ${typeof data}`);
      return false;
    }
    if (type === "integer" && !Number.isInteger(data)) {
      errors.push(`${path}: expected integer`);
      return false;
    }
    if (schema.minimum != null && data < schema.minimum) {
      errors.push(`${path}: ${data} < minimum ${schema.minimum}`);
      return false;
    }
    if (schema.maximum != null && data > schema.maximum) {
      errors.push(`${path}: ${data} > maximum ${schema.maximum}`);
      return false;
    }
    return true;
  }

  private static primitive(kind: string, guard: (d: any) => boolean) {
    return (data: any, _schema: OpenAPISchema, errors: string[], path: string): boolean => {
      if (guard(data)) return true;
      errors.push(`${path}: expected ${kind}, got ${typeof data}`);
      return false;
    };
  }

  private static checks: Record<
    string,
    (data: any, schema: OpenAPISchema, errors: string[], path: string) => boolean
  > = {
    object: (d, s, e, p) => SchemaValidator.object(d, s, e, p),
    array: (d, s, e, p) => SchemaValidator.array(d, s, e, p),
    string: (d, s, e, p) => SchemaValidator.text(d, s, e, p),
    number: (d, s, e, p) => SchemaValidator.number(d, s, e, p),
    integer: (d, s, e, p) => SchemaValidator.number(d, s, e, p),
    boolean: SchemaValidator.primitive("boolean", (d) => typeof d === "boolean"),
    null: SchemaValidator.primitive("null", (d) => d === null),
  };

  private static validate(data: any, schema: OpenAPISchema, errors: string[], path = "$"): boolean {
    if (!schema) return true;
    if (schema.nullable && data === null) return true;
    if (schema.allOf)
      return schema.allOf.every((s, i) => this.validate(data, s, errors, `${path}.allOf[${i}]`));
    if (schema.oneOf) return this.union(data, schema.oneOf, errors, path, "oneOf");
    if (schema.anyOf) return this.union(data, schema.anyOf, errors, path, "anyOf");

    const type = schema.type ?? (schema.properties ? "object" : undefined);
    if (!type) return true;
    if (schema.enum && !schema.enum.includes(data)) {
      errors.push(`${path}: ${JSON.stringify(data)} not in enum`);
      return false;
    }
    if (schema.const !== undefined && data !== schema.const) {
      errors.push(`${path}: expected const ${JSON.stringify(schema.const)}`);
      return false;
    }

    const check = SchemaValidator.checks[type];
    return check ? check(data, schema, errors, path) : true;
  }

  private static samplers: Record<string, (schema: OpenAPISchema) => any> = {
    object: (s) =>
      Object.fromEntries(
        Object.entries(s.properties ?? {}).map(([k, v]) => [k, SchemaValidator.sample(v)]),
      ),
    array: (s) => (s.items ? [SchemaValidator.sample(s.items)] : []),
    string: (s) => formats[s.format ?? ""] ?? "sample",
    number: (s) => s.minimum ?? 1,
    integer: (s) => s.minimum ?? 1,
    boolean: () => true,
  };

  private static sample(schema: OpenAPISchema): any {
    if (!schema) return null;
    if (schema.example !== undefined) return schema.example;
    if (schema.allOf) return schema.allOf.reduce((acc, s) => Object.assign(acc, this.sample(s)), {});
    if (schema.oneOf?.[0]) return this.sample(schema.oneOf[0]);
    if (schema.anyOf?.[0]) return this.sample(schema.anyOf[0]);
    if (schema.enum?.length) return schema.enum[0];
    if (schema.const !== undefined) return schema.const;

    const type = schema.type ?? (schema.properties ? "object" : undefined);
    const make = type ? SchemaValidator.samplers[type] : undefined;
    return make ? make(schema) : null;
  }

  static async getRouteResponseStatusCodes(path: string, method = "get"): Promise<number[]> {
    const spec = await this.getSpec();
    const apiPath = this.findOpenAPIPath(spec, path.startsWith("/") ? path : `/${path}`);
    if (!apiPath) return [];
    const responses = spec.paths?.[apiPath]?.[method.toLowerCase()]?.responses;
    return responses ? Object.keys(responses).map(Number) : [];
  }

  static async validateResponse(response: Response, path: string, method = "get"): Promise<any> {
    const spec = await this.getSpec();
    const data = await response.clone().json();
    const normalized = path.startsWith("/") ? path : `/${path}`;
    const apiPath = this.findOpenAPIPath(spec, normalized);

    if (!apiPath) {
      console.warn(`No OpenAPI path found for ${method.toUpperCase()} ${path}`);
      return data;
    }

    const operation = spec.paths?.[apiPath]?.[method.toLowerCase()];
    const responseSpec =
      operation?.responses?.[response.status]?.content?.["application/json"]?.schema;

    if (!responseSpec) {
      console.warn(`No response schema for ${method.toUpperCase()} ${path} [${response.status}]`);
      return data;
    }

    const resolved = this.resolve(responseSpec, spec);
    const errors: string[] = [];
    if (!this.validate(data, resolved, errors)) {
      throw new Error(
        `Response validation failed for ${method.toUpperCase()} ${path} [${response.status}]:\n  ${errors.join("\n  ")}`,
      );
    }

    return data;
  }

  private static async requestSchema(path: string, method: string): Promise<OpenAPISchema | null> {
    const spec = await this.getSpec();
    const apiPath = this.findOpenAPIPath(spec, path.startsWith("/") ? path : `/${path}`);
    if (!apiPath) return null;
    const schema =
      spec.paths?.[apiPath]?.[method.toLowerCase()]?.requestBody?.content?.["application/json"]
        ?.schema;
    return schema ? this.resolve(schema, spec) : null;
  }

  static async createInvalidRequestBody(path: string, method = "post"): Promise<any> {
    const resolved = await this.requestSchema(path, method);
    if (!resolved || resolved.type !== "object" || !resolved.required?.length || !resolved.properties)
      return null;

    const body = this.sample(resolved);
    const field = resolved.required[0]!;
    if (!body || !(field in body)) return null;

    delete body[field];
    return body;
  }
}
