// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  DeleteFileByNameErrors,
  DeleteFileByNameResponses,
  DeleteKeyByIdErrors,
  DeleteKeyByIdResponses,
  DeleteProjectByIdErrors,
  DeleteProjectByIdResponses,
  DeleteTodoByIdErrors,
  DeleteTodoByIdResponses,
  GetFileByNameContentErrors,
  GetFileByNameContentResponses,
  GetFileErrors,
  GetFileResponses,
  GetFileSignedErrors,
  GetFileSignedResponses,
  GetKeyErrors,
  GetKeyResponses,
  GetMeErrors,
  GetMeResponses,
  GetProjectByIdErrors,
  GetProjectByIdResponses,
  GetProjectErrors,
  GetProjectResponses,
  GetTodoByIdErrors,
  GetTodoByIdResponses,
  GetTodoErrors,
  GetTodoResponses,
  GetTodoStageErrors,
  GetTodoStageResponses,
  PatchFileByNameErrors,
  PatchFileByNameResponses,
  PatchProjectByIdErrors,
  PatchProjectByIdResponses,
  PatchTodoByIdErrors,
  PatchTodoByIdResponses,
  PostFileErrors,
  PostFileResponses,
  PostKeyErrors,
  PostKeyResponses,
  PostProjectErrors,
  PostProjectResponses,
  PostTodoErrors,
  PostTodoResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new TemplateSdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class TemplateSdk extends HeyApiClient {
  public static readonly __registry: HeyApiRegistry<TemplateSdk> =
    new HeyApiRegistry<TemplateSdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    TemplateSdk.__registry.set(this, args?.key);
  }

  /**
   * Get current user
   *
   * Get the profile of the currently authenticated user.
   */
  public getMe<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/me",
      ...options,
    });
  }

  /**
   * List keys
   *
   * List the current user's API keys. The key authenticating this request is flagged `current`.
   */
  public getKey<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetKeyResponses, GetKeyErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<GetKeyResponses, GetKeyErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/key",
      ...options,
    });
  }

  /**
   * Create key
   *
   * Mint a named API key for the current user. Pass `expiresInDays` to set an expiry; omit it for a key that never expires.
   */
  public postKey<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      expiresInDays?: number;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostKeyResponses, PostKeyErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "expiresInDays" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostKeyResponses, PostKeyErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/key",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Revoke key
   *
   * Revoke an API key. The secret stops authenticating immediately.
   */
  public deleteKeyById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteKeyByIdResponses, DeleteKeyByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteKeyByIdResponses,
      DeleteKeyByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/key/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * List todos
   *
   * List todos, optionally narrowed by status, assignee, stage or owning entity. Paginated.
   */
  public getTodo<ThrowOnError extends boolean = false>(
    parameters?: {
      page?: number;
      pageSize?: number;
      sort?: Array<
        | "title"
        | "-title"
        | "status"
        | "-status"
        | "stage"
        | "-stage"
        | "assignee"
        | "-assignee"
        | "startDate"
        | "-startDate"
        | "dueDate"
        | "-dueDate"
        | "timeCreated"
        | "-timeCreated"
      >;
      status?: "backlog" | "planned" | "active" | "blocked" | "done";
      assignee?: string;
      stage?: string;
      source?: string;
      sourceID?: string;
      createdBy?: string;
      search?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetTodoResponses, GetTodoErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "query", key: "page" },
            { in: "query", key: "pageSize" },
            { in: "query", key: "sort" },
            { in: "query", key: "status" },
            { in: "query", key: "assignee" },
            { in: "query", key: "stage" },
            { in: "query", key: "source" },
            { in: "query", key: "sourceID" },
            { in: "query", key: "createdBy" },
            { in: "query", key: "search" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<GetTodoResponses, GetTodoErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo",
      ...options,
      ...params,
    });
  }

  /**
   * Create todo
   */
  public postTodo<ThrowOnError extends boolean = false>(
    parameters: {
      title: string;
      body?: string | null;
      tags?: Array<string>;
      stage?: string | null;
      assignee?: string | null;
      source?: string | null;
      sourceID?: string | null;
      status?: "backlog" | "planned" | "active" | "blocked" | "done";
      startDate?: string | null;
      dueDate?: string | null;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostTodoResponses, PostTodoErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "title" },
            { in: "body", key: "body" },
            { in: "body", key: "tags" },
            { in: "body", key: "stage" },
            { in: "body", key: "assignee" },
            { in: "body", key: "source" },
            { in: "body", key: "sourceID" },
            { in: "body", key: "status" },
            { in: "body", key: "startDate" },
            { in: "body", key: "dueDate" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostTodoResponses, PostTodoErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List stages
   *
   * The stage labels in use, with the span and counts derived from the todos in each.
   */
  public getTodoStage<ThrowOnError extends boolean = false>(
    parameters?: {
      source?: string;
      sourceID?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetTodoStageResponses, GetTodoStageErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "query", key: "source" },
            { in: "query", key: "sourceID" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetTodoStageResponses,
      GetTodoStageErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/stage",
      ...options,
      ...params,
    });
  }

  /**
   * Delete todo
   */
  public deleteTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteTodoByIdResponses, DeleteTodoByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteTodoByIdResponses,
      DeleteTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get todo
   */
  public getTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetTodoByIdResponses, GetTodoByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).get<
      GetTodoByIdResponses,
      GetTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Update todo
   */
  public patchTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
      title?: string;
      body?: string | null;
      tags?: Array<string>;
      stage?: string | null;
      status?: "backlog" | "planned" | "active" | "blocked" | "done";
      reason?: string | null;
      startDate?: string | null;
      dueDate?: string | null;
      assignee?: string | null;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PatchTodoByIdResponses, PatchTodoByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "path", key: "id" },
            { in: "body", key: "title" },
            { in: "body", key: "body" },
            { in: "body", key: "tags" },
            { in: "body", key: "stage" },
            { in: "body", key: "status" },
            { in: "body", key: "reason" },
            { in: "body", key: "startDate" },
            { in: "body", key: "dueDate" },
            { in: "body", key: "assignee" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchTodoByIdResponses,
      PatchTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List projects
   *
   * List projects, optionally filtered by name. Paginated.
   */
  public getProject<ThrowOnError extends boolean = false>(
    parameters?: {
      page?: number;
      pageSize?: number;
      sort?: Array<"name" | "-name" | "timeCreated" | "-timeCreated">;
      search?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetProjectResponses, GetProjectErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "query", key: "page" },
            { in: "query", key: "pageSize" },
            { in: "query", key: "sort" },
            { in: "query", key: "search" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetProjectResponses,
      GetProjectErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/project",
      ...options,
      ...params,
    });
  }

  /**
   * Create project
   */
  public postProject<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      description?: string | null;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostProjectResponses, PostProjectErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "description" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostProjectResponses,
      PostProjectErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/project",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Delete project
   */
  public deleteProjectById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteProjectByIdResponses, DeleteProjectByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteProjectByIdResponses,
      DeleteProjectByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/project/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get project
   */
  public getProjectById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetProjectByIdResponses, GetProjectByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).get<
      GetProjectByIdResponses,
      GetProjectByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/project/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Update project
   */
  public patchProjectById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
      name?: string;
      description?: string | null;
      image?: string | null;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PatchProjectByIdResponses, PatchProjectByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "path", key: "id" },
            { in: "body", key: "name" },
            { in: "body", key: "description" },
            { in: "body", key: "image" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchProjectByIdResponses,
      PatchProjectByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/project/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List files
   *
   * Everything under the user's prefix on the default disk, newest first.
   */
  public getFile<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetFileResponses, GetFileErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<GetFileResponses, GetFileErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file",
      ...options,
    });
  }

  /**
   * Upload file
   *
   * Multipart form with a `file` field. The filename becomes the key, so re-uploading the same name overwrites.
   */
  public postFile<ThrowOnError extends boolean = false>(
    parameters: {
      file: Blob | File;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostFileResponses, PostFileErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "body", key: "file" }] }]);
    return (options?.client ?? this.client).post<PostFileResponses, PostFileErrors, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file",
      ...options,
      ...params,
      headers: {
        "Content-Type": null,
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Get signed file content
   *
   * Serves the bytes for a `temporaryUrl` minted by a disk that can't presign (fs, R2 binding). The signature stands in for the session, so no token is needed.
   */
  public getFileSigned<ThrowOnError extends boolean = false>(
    parameters: {
      key: string;
      expires: number;
      kid: string;
      sig: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetFileSignedResponses, GetFileSignedErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "query", key: "key" },
            { in: "query", key: "expires" },
            { in: "query", key: "kid" },
            { in: "query", key: "sig" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetFileSignedResponses,
      GetFileSignedErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/signed",
      ...options,
      ...params,
    });
  }

  /**
   * Get file content
   *
   * Redirects to a presigned storage URL when the disk supports it; streams the bytes otherwise.
   */
  public getFileByNameContent<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetFileByNameContentResponses, GetFileByNameContentErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "name" }] }]);
    return (options?.client ?? this.client).get<
      GetFileByNameContentResponses,
      GetFileByNameContentErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/{name}/content",
      ...options,
      ...params,
    });
  }

  /**
   * Delete file
   */
  public deleteFileByName<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteFileByNameResponses, DeleteFileByNameErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "name" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteFileByNameResponses,
      DeleteFileByNameErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/{name}",
      ...options,
      ...params,
    });
  }

  /**
   * Rename file
   *
   * Moves the object to a new key under the same prefix.
   */
  public patchFileByName<ThrowOnError extends boolean = false>(
    parameters: {
      path_name: string;
      body_name: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PatchFileByNameResponses, PatchFileByNameErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            {
              in: "path",
              key: "path_name",
              map: "name",
            },
            {
              in: "body",
              key: "body_name",
              map: "name",
            },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchFileByNameResponses,
      PatchFileByNameErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/{name}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }
}
