// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  DeleteFileByIdErrors,
  DeleteFileByIdResponses,
  DeleteKeyByIdErrors,
  DeleteKeyByIdResponses,
  DeleteOrganizationInvitationByIdErrors,
  DeleteOrganizationInvitationByIdResponses,
  DeleteOrganizationMemberByIdErrors,
  DeleteOrganizationMemberByIdResponses,
  DeleteOrganizationRoleByIdErrors,
  DeleteOrganizationRoleByIdResponses,
  DeleteTodoByIdErrors,
  DeleteTodoByIdResponses,
  GetFileByIdContentErrors,
  GetFileByIdContentResponses,
  GetFileByIdErrors,
  GetFileByIdResponses,
  GetFileErrors,
  GetFileResponses,
  GetKeyErrors,
  GetKeyResponses,
  GetMeErrors,
  GetMeResponses,
  GetOrganizationErrors,
  GetOrganizationInvitationErrors,
  GetOrganizationInvitationResponses,
  GetOrganizationMemberErrors,
  GetOrganizationMemberResponses,
  GetOrganizationResponses,
  GetOrganizationRoleErrors,
  GetOrganizationRoleResponses,
  GetTodoByIdErrors,
  GetTodoByIdResponses,
  GetTodoErrors,
  GetTodoResponses,
  PatchFileByIdErrors,
  PatchFileByIdResponses,
  PatchOrganizationErrors,
  PatchOrganizationMemberByIdErrors,
  PatchOrganizationMemberByIdResponses,
  PatchOrganizationResponses,
  PatchOrganizationRoleByIdErrors,
  PatchOrganizationRoleByIdResponses,
  PatchTodoByIdErrors,
  PatchTodoByIdResponses,
  PostFileErrors,
  PostFileResponses,
  PostKeyErrors,
  PostKeyResponses,
  PostOrganizationErrors,
  PostOrganizationInvitationErrors,
  PostOrganizationInvitationResponses,
  PostOrganizationResponses,
  PostOrganizationRoleErrors,
  PostOrganizationRoleResponses,
  PostTodoErrors,
  PostTodoResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new TemplateSdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class TemplateSdk extends HeyApiClient {
  public static readonly __registry: HeyApiRegistry<TemplateSdk> =
    new HeyApiRegistry<TemplateSdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    TemplateSdk.__registry.set(this, args?.key);
  }

  /**
   * Get current user
   *
   * Get the profile of the currently authenticated user.
   */
  public getMe<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/me",
      ...options,
    });
  }

  /**
   * List keys
   *
   * List the current user's API keys. The key authenticating this request is flagged `current`.
   */
  public getKey<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetKeyResponses, GetKeyErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<GetKeyResponses, GetKeyErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/key",
      ...options,
    });
  }

  /**
   * Create key
   *
   * Mint a named API key for the current user. Pass `expiresInDays` to set an expiry; omit it for a key that never expires. `roleID` scopes the key to a role in one of your orgs; without it the key takes your own role in the org named by `X-Org-ID`. The role's permissions must not exceed yours.
   */
  public postKey<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      expiresInDays?: number;
      roleID?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostKeyResponses, PostKeyErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "expiresInDays" },
            { in: "body", key: "roleID" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostKeyResponses, PostKeyErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/key",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Revoke key
   *
   * Revoke an API key. The secret stops authenticating immediately.
   */
  public deleteKeyById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteKeyByIdResponses, DeleteKeyByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteKeyByIdResponses,
      DeleteKeyByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/key/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * List todos
   *
   * List the current user's todos, optionally filtered by state. Paginated.
   */
  public getTodo<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      page?: number;
      pageSize?: number;
      state?: "open" | "closed";
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetTodoResponses, GetTodoErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "query", key: "page" },
            { in: "query", key: "pageSize" },
            { in: "query", key: "state" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<GetTodoResponses, GetTodoErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo",
      ...options,
      ...params,
    });
  }

  /**
   * Create todo
   */
  public postTodo<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      title: string;
      body?: string | null;
      tags?: Array<string>;
      dueDate?: string | null;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostTodoResponses, PostTodoErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "body", key: "title" },
            { in: "body", key: "body" },
            { in: "body", key: "tags" },
            { in: "body", key: "dueDate" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostTodoResponses, PostTodoErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Delete todo
   */
  public deleteTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteTodoByIdResponses, DeleteTodoByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).delete<
      DeleteTodoByIdResponses,
      DeleteTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get todo
   */
  public getTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetTodoByIdResponses, GetTodoByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetTodoByIdResponses,
      GetTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Update todo
   */
  public patchTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
      title?: string;
      body?: string | null;
      tags?: Array<string>;
      dueDate?: string | null;
      state?: "open" | "closed";
      stateReason?: "completed" | "not_planned" | null;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PatchTodoByIdResponses, PatchTodoByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
            { in: "body", key: "title" },
            { in: "body", key: "body" },
            { in: "body", key: "tags" },
            { in: "body", key: "dueDate" },
            { in: "body", key: "state" },
            { in: "body", key: "stateReason" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchTodoByIdResponses,
      PatchTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List files
   *
   * The user's files, newest first. Filter by tags (comma-separated) or search.
   */
  public getFile<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      page?: number;
      pageSize?: number;
      tags?: string;
      search?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetFileResponses, GetFileErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "query", key: "page" },
            { in: "query", key: "pageSize" },
            { in: "query", key: "tags" },
            { in: "query", key: "search" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<GetFileResponses, GetFileErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file",
      ...options,
      ...params,
    });
  }

  /**
   * Upload file
   *
   * Multipart form with a `file` field, plus optional `tags` (comma-separated).
   */
  public postFile<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      file: Blob | File;
      tags?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostFileResponses, PostFileErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "body", key: "file" },
            { in: "body", key: "tags" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostFileResponses, PostFileErrors, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file",
      ...options,
      ...params,
      headers: {
        "Content-Type": null,
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Delete file
   */
  public deleteFileById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteFileByIdResponses, DeleteFileByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).delete<
      DeleteFileByIdResponses,
      DeleteFileByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get file metadata
   */
  public getFileById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetFileByIdResponses, GetFileByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetFileByIdResponses,
      GetFileByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Update file
   *
   * Rename or re-tag a file.
   */
  public patchFileById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
      filename?: string;
      tags?: Array<string>;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PatchFileByIdResponses, PatchFileByIdErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
            { in: "body", key: "filename" },
            { in: "body", key: "tags" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchFileByIdResponses,
      PatchFileByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Get file content
   *
   * Redirects to a presigned storage URL when the backend supports it; streams the bytes otherwise.
   */
  public getFileByIdContent<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetFileByIdContentResponses, GetFileByIdContentErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<
      GetFileByIdContentResponses,
      GetFileByIdContentErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/file/{id}/content",
      ...options,
      ...params,
    });
  }

  /**
   * List organizations
   *
   * List the organizations the current user belongs to. Org-scoped routes name one of them with the `X-Org-ID` header.
   */
  public getOrganization<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetOrganizationResponses, GetOrganizationErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<
      GetOrganizationResponses,
      GetOrganizationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization",
      ...options,
    });
  }

  /**
   * Update organization
   *
   * Rename the active organization. Requires the `org:manage` permission.
   */
  public patchOrganization<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      name: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PatchOrganizationResponses, PatchOrganizationErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "body", key: "name" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchOrganizationResponses,
      PatchOrganizationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Create organization
   *
   * Create an organization owned by the current user, with default roles seeded.
   */
  public postOrganization<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostOrganizationResponses, PostOrganizationErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: "body", key: "name" }] }]);
    return (options?.client ?? this.client).post<
      PostOrganizationResponses,
      PostOrganizationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List members
   *
   * List members of the active organization. Requires `member:read`.
   */
  public getOrganizationMember<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetOrganizationMemberResponses, GetOrganizationMemberErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [{ args: [{ in: "headers", key: "X-Org-ID" }] }],
    );
    return (options?.client ?? this.client).get<
      GetOrganizationMemberResponses,
      GetOrganizationMemberErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/member",
      ...options,
      ...params,
    });
  }

  /**
   * Remove member
   *
   * Remove a member from the active organization. Requires `member:manage`.
   */
  public deleteOrganizationMemberById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    DeleteOrganizationMemberByIdResponses,
    DeleteOrganizationMemberByIdErrors,
    ThrowOnError
  > {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).delete<
      DeleteOrganizationMemberByIdResponses,
      DeleteOrganizationMemberByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/member/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Assign role
   *
   * Assign a role to a member. Requires `member:manage`.
   */
  public patchOrganizationMemberById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
      roleID: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    PatchOrganizationMemberByIdResponses,
    PatchOrganizationMemberByIdErrors,
    ThrowOnError
  > {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
            { in: "body", key: "roleID" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchOrganizationMemberByIdResponses,
      PatchOrganizationMemberByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/member/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List roles
   *
   * List the active organization's roles. Requires `member:read`.
   */
  public getOrganizationRole<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetOrganizationRoleResponses, GetOrganizationRoleErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [{ args: [{ in: "headers", key: "X-Org-ID" }] }],
    );
    return (options?.client ?? this.client).get<
      GetOrganizationRoleResponses,
      GetOrganizationRoleErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/role",
      ...options,
      ...params,
    });
  }

  /**
   * Create role
   *
   * Create a custom role. Requires `role:manage`. Permissions: todo:read, todo:write, file:read, file:write, member:read, member:manage, role:manage, invite:manage, org:manage.
   */
  public postOrganizationRole<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      name: string;
      permissions: Array<
        | "todo:read"
        | "todo:write"
        | "file:read"
        | "file:write"
        | "member:read"
        | "member:manage"
        | "role:manage"
        | "invite:manage"
        | "org:manage"
      >;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PostOrganizationRoleResponses, PostOrganizationRoleErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "body", key: "name" },
            { in: "body", key: "permissions" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostOrganizationRoleResponses,
      PostOrganizationRoleErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/role",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Remove role
   *
   * Delete an unused role. Requires `role:manage`.
   */
  public deleteOrganizationRoleById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    DeleteOrganizationRoleByIdResponses,
    DeleteOrganizationRoleByIdErrors,
    ThrowOnError
  > {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).delete<
      DeleteOrganizationRoleByIdResponses,
      DeleteOrganizationRoleByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/role/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Update role
   *
   * Rename a role or change its permissions. Requires `role:manage`.
   */
  public patchOrganizationRoleById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
      name?: string;
      permissions?: Array<
        | "todo:read"
        | "todo:write"
        | "file:read"
        | "file:write"
        | "member:read"
        | "member:manage"
        | "role:manage"
        | "invite:manage"
        | "org:manage"
      >;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    PatchOrganizationRoleByIdResponses,
    PatchOrganizationRoleByIdErrors,
    ThrowOnError
  > {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
            { in: "body", key: "name" },
            { in: "body", key: "permissions" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchOrganizationRoleByIdResponses,
      PatchOrganizationRoleByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/role/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * List invitations
   *
   * List pending invitations. Requires `invite:manage`.
   */
  public getOrganizationInvitation<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    GetOrganizationInvitationResponses,
    GetOrganizationInvitationErrors,
    ThrowOnError
  > {
    const params = buildClientParams(
      [parameters],
      [{ args: [{ in: "headers", key: "X-Org-ID" }] }],
    );
    return (options?.client ?? this.client).get<
      GetOrganizationInvitationResponses,
      GetOrganizationInvitationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/invitation",
      ...options,
      ...params,
    });
  }

  /**
   * Invite member
   *
   * Invite an email to join the active organization with a role. Requires `invite:manage`.
   */
  public postOrganizationInvitation<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      email: string;
      roleID: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    PostOrganizationInvitationResponses,
    PostOrganizationInvitationErrors,
    ThrowOnError
  > {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "body", key: "email" },
            { in: "body", key: "roleID" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostOrganizationInvitationResponses,
      PostOrganizationInvitationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/invitation",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Revoke invitation
   *
   * Revoke a pending invitation. Requires `invite:manage`.
   */
  public deleteOrganizationInvitationById<ThrowOnError extends boolean = false>(
    parameters: {
      "X-Org-ID": string;
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    DeleteOrganizationInvitationByIdResponses,
    DeleteOrganizationInvitationByIdErrors,
    ThrowOnError
  > {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "headers", key: "X-Org-ID" },
            { in: "path", key: "id" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).delete<
      DeleteOrganizationInvitationByIdResponses,
      DeleteOrganizationInvitationByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/organization/invitation/{id}",
      ...options,
      ...params,
    });
  }
}
