// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  DeleteTodoByIdErrors,
  DeleteTodoByIdResponses,
  GetMeErrors,
  GetMeResponses,
  GetTodoByIdErrors,
  GetTodoByIdResponses,
  GetTodoErrors,
  GetTodoResponses,
  PatchTodoByIdErrors,
  PatchTodoByIdResponses,
  PostAuthLoginErrors,
  PostAuthLoginResponses,
  PostAuthLogoutErrors,
  PostAuthLogoutResponses,
  PostAuthRegisterErrors,
  PostAuthRegisterResponses,
  PostTodoErrors,
  PostTodoResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new TemplateSdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class TemplateSdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<TemplateSdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    TemplateSdk.__registry.set(this, args?.key);
  }

  /**
   * Get current user
   *
   * Get the profile of the currently authenticated user.
   */
  public getMe<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) {
    return (options?.client ?? this.client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/me",
      ...options,
    });
  }

  /**
   * Register
   *
   * Create a new user with an email/password and start a session.
   */
  public postAuthRegister<ThrowOnError extends boolean = false>(
    parameters: {
      name: string;
      email: string;
      password: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "name" },
            { in: "body", key: "email" },
            { in: "body", key: "password" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostAuthRegisterResponses,
      PostAuthRegisterErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/auth/register",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Login
   *
   * Exchange an email/password for a new session.
   */
  public postAuthLogin<ThrowOnError extends boolean = false>(
    parameters: {
      email: string;
      password: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "email" },
            { in: "body", key: "password" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      PostAuthLoginResponses,
      PostAuthLoginErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/auth/login",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Logout
   *
   * Invalidate the current session.
   */
  public postAuthLogout<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).post<
      PostAuthLogoutResponses,
      PostAuthLogoutErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/auth/logout",
      ...options,
    });
  }

  /**
   * List todos
   *
   * List the current user's todos, optionally filtered by status. Paginated.
   */
  public getTodo<ThrowOnError extends boolean = false>(
    parameters?: {
      page?: number;
      pageSize?: number;
      status?: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "query", key: "page" },
            { in: "query", key: "pageSize" },
            { in: "query", key: "status" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<GetTodoResponses, GetTodoErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo",
      ...options,
      ...params,
    });
  }

  /**
   * Create todo
   */
  public postTodo<ThrowOnError extends boolean = false>(
    parameters: {
      title: string;
      status?: string;
      dueDate?: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "body", key: "title" },
            { in: "body", key: "status" },
            { in: "body", key: "dueDate" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<PostTodoResponses, PostTodoErrors, ThrowOnError>({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Delete todo
   */
  public deleteTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).delete<
      DeleteTodoByIdResponses,
      DeleteTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Get todo
   */
  public getTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams([parameters], [{ args: [{ in: "path", key: "id" }] }]);
    return (options?.client ?? this.client).get<
      GetTodoByIdResponses,
      GetTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
    });
  }

  /**
   * Update todo
   */
  public patchTodoById<ThrowOnError extends boolean = false>(
    parameters: {
      id: string;
      title?: string;
      status?: string;
      dueDate?: string;
    },
    options?: Options<never, ThrowOnError>,
  ) {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: "path", key: "id" },
            { in: "body", key: "title" },
            { in: "body", key: "status" },
            { in: "body", key: "dueDate" },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).patch<
      PatchTodoByIdResponses,
      PatchTodoByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/todo/{id}",
      ...options,
      ...params,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
        ...params.headers,
      },
    });
  }
}
