// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | (string & {});
};

/**
 * A user account.
 */
export type User = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  name: string;
  email: string;
  emailVerified?: boolean;
  image: string | null;
};

/**
 * Not found error
 */
export type ErrorResponse = {
  /**
   * The error type category
   */
  type: "validation" | "authentication" | "forbidden" | "not_found" | "rate_limit" | "internal";
  /**
   * Machine-readable error code identifier
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * The parameter that caused the error (if applicable)
   */
  param?: string;
  /**
   * Additional error context information
   */
  details?: unknown;
};

/**
 * An API key belonging to a user.
 */
export type Key = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  name: string;
  /**
   * The secret. Handed back in full so it can be copied.
   */
  key: string;
  /**
   * Masked secret, safe to show in a list.
   */
  display: string;
  /**
   * When the key last authenticated a request.
   */
  timeUsed: string | null;
  /**
   * When the key stops working. Null means it never expires.
   */
  expiresAt: string | null;
  /**
   * Whether this is the key authenticating the current request.
   */
  current: boolean;
};

/**
 * A todo item that belongs to a user.
 */
export type Todo = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  userID: string;
  title: string;
  body: string | null;
  state: "open" | "closed";
  stateReason: "completed" | "not_planned" | null;
  tags: Array<string>;
  dueDate: string | null;
};

/**
 * An uploaded file that belongs to a user.
 */
export type File = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  userID: string;
  filename: string;
  contentType: string;
  size: number;
  tags: Array<string>;
  timeCreated: string;
};

export type GetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/me";
};

export type GetMeErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
  /**
   * The current user.
   */
  200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetKeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/key";
};

export type GetKeyErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetKeyError = GetKeyErrors[keyof GetKeyErrors];

export type GetKeyResponses = {
  /**
   * The user's keys.
   */
  200: Array<Key>;
};

export type GetKeyResponse = GetKeyResponses[keyof GetKeyResponses];

export type PostKeyData = {
  body: {
    name: string;
    expiresInDays?: number;
  };
  path?: never;
  query?: never;
  url: "/key";
};

export type PostKeyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostKeyError = PostKeyErrors[keyof PostKeyErrors];

export type PostKeyResponses = {
  /**
   * The created key, including its secret.
   */
  200: Key;
};

export type PostKeyResponse = PostKeyResponses[keyof PostKeyResponses];

export type DeleteKeyByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/key/{id}";
};

export type DeleteKeyByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteKeyByIdError = DeleteKeyByIdErrors[keyof DeleteKeyByIdErrors];

export type DeleteKeyByIdResponses = {
  /**
   * Revoked.
   */
  200: "ok";
};

export type DeleteKeyByIdResponse = DeleteKeyByIdResponses[keyof DeleteKeyByIdResponses];

export type GetTodoData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    state?: "open" | "closed";
  };
  url: "/todo";
};

export type GetTodoErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetTodoError = GetTodoErrors[keyof GetTodoErrors];

export type GetTodoResponses = {
  /**
   * A page of results.
   */
  200: {
    data: Array<Todo>;
    /**
     * Page number returned.
     */
    page: number;
    /**
     * Number of entities per page.
     */
    pageSize: number;
    /**
     * Total number of matching entities across all pages.
     */
    total: number;
  };
};

export type GetTodoResponse = GetTodoResponses[keyof GetTodoResponses];

export type PostTodoData = {
  body: {
    title: string;
    body?: string | null;
    tags?: Array<string>;
    dueDate?: string | null;
  };
  path?: never;
  query?: never;
  url: "/todo";
};

export type PostTodoErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostTodoError = PostTodoErrors[keyof PostTodoErrors];

export type PostTodoResponses = {
  /**
   * The created todo.
   */
  200: Todo;
};

export type PostTodoResponse = PostTodoResponses[keyof PostTodoResponses];

export type DeleteTodoByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/todo/{id}";
};

export type DeleteTodoByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteTodoByIdError = DeleteTodoByIdErrors[keyof DeleteTodoByIdErrors];

export type DeleteTodoByIdResponses = {
  /**
   * Deleted.
   */
  200: "ok";
};

export type DeleteTodoByIdResponse = DeleteTodoByIdResponses[keyof DeleteTodoByIdResponses];

export type GetTodoByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/todo/{id}";
};

export type GetTodoByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetTodoByIdError = GetTodoByIdErrors[keyof GetTodoByIdErrors];

export type GetTodoByIdResponses = {
  /**
   * The todo.
   */
  200: Todo;
};

export type GetTodoByIdResponse = GetTodoByIdResponses[keyof GetTodoByIdResponses];

export type PatchTodoByIdData = {
  body: {
    title?: string;
    body?: string | null;
    tags?: Array<string>;
    dueDate?: string | null;
    state?: "open" | "closed";
    stateReason?: "completed" | "not_planned" | null;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/todo/{id}";
};

export type PatchTodoByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PatchTodoByIdError = PatchTodoByIdErrors[keyof PatchTodoByIdErrors];

export type PatchTodoByIdResponses = {
  /**
   * The updated todo.
   */
  200: Todo;
};

export type PatchTodoByIdResponse = PatchTodoByIdResponses[keyof PatchTodoByIdResponses];

export type GetFileData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    tags?: string;
    search?: string;
  };
  url: "/file";
};

export type GetFileErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
  /**
   * A page of results.
   */
  200: {
    data: Array<File>;
    /**
     * Page number returned.
     */
    page: number;
    /**
     * Number of entities per page.
     */
    pageSize: number;
    /**
     * Total number of matching entities across all pages.
     */
    total: number;
  };
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type PostFileData = {
  body?: {
    file: Blob | File;
    tags?: string;
  };
  path?: never;
  query?: never;
  url: "/file";
};

export type PostFileErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostFileError = PostFileErrors[keyof PostFileErrors];

export type PostFileResponses = {
  /**
   * The uploaded file.
   */
  200: File;
};

export type PostFileResponse = PostFileResponses[keyof PostFileResponses];

export type DeleteFileByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/file/{id}";
};

export type DeleteFileByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteFileByIdError = DeleteFileByIdErrors[keyof DeleteFileByIdErrors];

export type DeleteFileByIdResponses = {
  /**
   * Deleted.
   */
  200: "ok";
};

export type DeleteFileByIdResponse = DeleteFileByIdResponses[keyof DeleteFileByIdResponses];

export type GetFileByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/file/{id}";
};

export type GetFileByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetFileByIdError = GetFileByIdErrors[keyof GetFileByIdErrors];

export type GetFileByIdResponses = {
  /**
   * The file's metadata.
   */
  200: File;
};

export type GetFileByIdResponse = GetFileByIdResponses[keyof GetFileByIdResponses];

export type PatchFileByIdData = {
  body: {
    filename?: string;
    tags?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/file/{id}";
};

export type PatchFileByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PatchFileByIdError = PatchFileByIdErrors[keyof PatchFileByIdErrors];

export type PatchFileByIdResponses = {
  /**
   * The updated file.
   */
  200: File;
};

export type PatchFileByIdResponse = PatchFileByIdResponses[keyof PatchFileByIdResponses];

export type GetFileByIdContentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/file/{id}/content";
};

export type GetFileByIdContentErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetFileByIdContentError = GetFileByIdContentErrors[keyof GetFileByIdContentErrors];

export type GetFileByIdContentResponses = {
  /**
   * The raw file bytes.
   */
  200: unknown;
};
