// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | (string & {});
};

/**
 * A user account.
 */
export type User = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image: string | null;
};

/**
 * Not found error
 */
export type ErrorResponse = {
  /**
   * The error type category
   */
  type: "validation" | "authentication" | "forbidden" | "not_found" | "rate_limit" | "internal";
  /**
   * Machine-readable error code identifier
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * The parameter that caused the error (if applicable)
   */
  param?: string;
  /**
   * Additional error context information
   */
  details?: unknown;
};

/**
 * A todo item that belongs to a user.
 */
export type Todo = {
  /**
   * Unique object identifier.
   * The format and length of IDs may change over time.
   */
  id: string;
  userID: string;
  title: string;
  /**
   * Status of a todo item. Any short label; defaults are pending, in_progress and done.
   */
  status: string;
  dueDate: string | null;
};

export type GetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/me";
};

export type GetMeErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
  /**
   * The current user.
   */
  200: User;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type PostAuthRegisterData = {
  body: {
    name: string;
    email: string;
    password: string;
  };
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type PostAuthRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
  /**
   * New session.
   */
  200: {
    /**
     * The logged-in user's ID.
     */
    userID: string;
    /**
     * Bearer session token. Include as `Authorization: Bearer <token>`.
     */
    token: string;
  };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
  body: {
    email: string;
    password: string;
  };
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type PostAuthLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
  /**
   * New session.
   */
  200: {
    /**
     * The logged-in user's ID.
     */
    userID: string;
    /**
     * Bearer session token. Include as `Authorization: Bearer <token>`.
     */
    token: string;
  };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type PostAuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
  /**
   * Logged out.
   */
  200: "ok";
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetTodoData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    /**
     * Status of a todo item. Any short label; defaults are pending, in_progress and done.
     */
    status?: string;
  };
  url: "/todo";
};

export type GetTodoErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetTodoError = GetTodoErrors[keyof GetTodoErrors];

export type GetTodoResponses = {
  /**
   * A page of results.
   */
  200: {
    data: Array<Todo>;
    /**
     * Page number returned.
     */
    page: number;
    /**
     * Number of entities per page.
     */
    pageSize: number;
    /**
     * Total number of matching entities across all pages.
     */
    total: number;
  };
};

export type GetTodoResponse = GetTodoResponses[keyof GetTodoResponses];

export type PostTodoData = {
  body: {
    title: string;
    /**
     * Status of a todo item. Any short label; defaults are pending, in_progress and done.
     */
    status?: string;
    dueDate?: string;
  };
  path?: never;
  query?: never;
  url: "/todo";
};

export type PostTodoErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PostTodoError = PostTodoErrors[keyof PostTodoErrors];

export type PostTodoResponses = {
  /**
   * The created todo.
   */
  200: Todo;
};

export type PostTodoResponse = PostTodoResponses[keyof PostTodoResponses];

export type DeleteTodoByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/todo/{id}";
};

export type DeleteTodoByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteTodoByIdError = DeleteTodoByIdErrors[keyof DeleteTodoByIdErrors];

export type DeleteTodoByIdResponses = {
  /**
   * Deleted.
   */
  200: "ok";
};

export type DeleteTodoByIdResponse = DeleteTodoByIdResponses[keyof DeleteTodoByIdResponses];

export type GetTodoByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/todo/{id}";
};

export type GetTodoByIdErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetTodoByIdError = GetTodoByIdErrors[keyof GetTodoByIdErrors];

export type GetTodoByIdResponses = {
  /**
   * The todo.
   */
  200: Todo;
};

export type GetTodoByIdResponse = GetTodoByIdResponses[keyof GetTodoByIdResponses];

export type PatchTodoByIdData = {
  body: {
    title?: string;
    /**
     * Status of a todo item. Any short label; defaults are pending, in_progress and done.
     */
    status?: string;
    dueDate?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/todo/{id}";
};

export type PatchTodoByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type PatchTodoByIdError = PatchTodoByIdErrors[keyof PatchTodoByIdErrors];

export type PatchTodoByIdResponses = {
  /**
   * The updated todo.
   */
  200: Todo;
};

export type PatchTodoByIdResponse = PatchTodoByIdResponses[keyof PatchTodoByIdResponses];
